# BioDYM Material Flow Analysis - Scientific Notebook

A streamlined notebook for Material Flow Analysis using the BioDYM framework with enhanced plotting capabilities.

## Workflow Overview

This notebook follows a structured approach to Material Flow Analysis:

1. **Setup and Data Loading** - Prepare environment and load input data
2. **Calculation & Validation** - Execute MFA analysis and verify results
3. **Visualization** - Comprehensive analysis and exploration
4. **Export** - Save results and generate documentation

---

# 1. Setup and Data Loading

This section prepares the analysis environment and loads the input data.

## 1.1 Environment Setup

In [68]:
import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from IPython.display import display, HTML, Markdown

In [69]:
# Add BioDYM modules to path
src_path = os.path.join(os.getcwd(), 'src')
sys.path.insert(0, src_path)

In [70]:
# Add ODYM framework to path
biodym_mfa_tool_dir = os.getcwd()
odym_path = os.path.join(
    biodym_mfa_tool_dir, "framework", "ODYM-master_20241127", "odym", "modules"
)
sys.path.insert(0, odym_path)

In [71]:
# Add bioDYM add-on to path
biodym_addon_path = os.path.join(
    biodym_mfa_tool_dir, "framework", "bioDYM_add-on", "modules"
)
sys.path.insert(0, biodym_addon_path)

In [72]:
# Import BioDYM modules
try:
    import config
    import data_loader
    import system_setup
    import utils
    from engine import solver
    import plotting
    import ODYM_Classes as msc
    print("✅ BioDYM modules imported successfully")
except ImportError as e:
    print(f"❌ Import error: {e}")
    raise

✅ BioDYM modules imported successfully

In [73]:
# Set up plotting
plt.style.use('default')
print("📊 Plotting environment ready")

📊 Plotting environment ready

## 1.2 Data Input Configuration

**Change this variable to your Excel file:**

In [74]:
input_file = "data/01_input/250714_Template_CS1.xlsx"

In [75]:
print(f"📁 Input file: {input_file}")

📁 Input file: data/01_input/250714_Template_CS1.xlsx

## 1.3 Data Loading and Validation

In [76]:
print("\n" + "="*60)
print("📊 LOADING AND VALIDATING DATA")
print("="*60)

============================================================
📊 LOADING AND VALIDATING DATA
============================================================

In [77]:
# Load Excel file
try:
    input_data = pd.read_excel(
        input_file,
        sheet_name=None,
        header=0,
        engine='openpyxl',
        na_values=['N.A.', 'NA', 'n/a']
    )
    print(f"✅ Excel file loaded: {len(input_data)} sheets")
except Exception as e:
    print(f"❌ Error loading file: {e}")
    raise

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

✅ Excel file loaded: 20 sheets

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

In [78]:
# Display sheet overview
print("\n📋 Sheet Overview:")
for sheet_name, df in input_data.items():
    print(f"   {sheet_name}: {df.shape[0]} rows × {df.shape[1]} columns")

📋 Sheet Overview:
   Version_CS0_07.07.: 0 rows × 0 columns
   0_ReadMe: 73 rows × 20 columns
   Table of Content: 26 rows × 2 columns
   0_Configuration: 25 rows × 3 columns
   1_1_Definition_Flows: 82 rows × 22 columns
   1_2_Data_Flows: 349 rows × 37 columns
   2_1_Definition_Processes: 57 rows × 38 columns
   2_3_Process_TCs: 63 rows × 21 columns
   2_5_dynamic_tcs: 150 rows × 64 columns
   3_1_Definition_DSM: 50 rows × 18 columns
   2_4_Initial_Stock: 62 rows × 21 columns
   2_6_Stock_Outflow_TCs: 0 rows × 0 columns
   3_2_Definition_FOMP: 46 rows × 13 columns
   4_1_Uncertainty_Parameters: 12 rows × 10 columns
   3. TC_Data: 0 rows × 0 columns
   PX - Template: 71 rows × 13 columns
   4. Calculation_factors>>>>: 0 rows × 0 columns
   4. Codelists>>>>: 0 rows × 1 columns
   4_1 Codelists: 68 rows × 12 columns
   5. Wastefiles >>>>: 0 rows × 1 columns

In [79]:
# Validate required sheets
required_sheets = [
    '1_1_Definition_Flows',
    '1_2_Data_Flows', 
    '2_1_Definition_Processes',
    '2_4_Initial_Stock',  # Correct sheet name
    '2_5_dynamic_tcs'
]

In [80]:
missing_sheets = [sheet for sheet in required_sheets if sheet not in input_data.keys()]
if missing_sheets:
    print(f"\n⚠️ Missing required sheets: {missing_sheets}")
else:
    print("\n✅ All required sheets present")

✅ All required sheets present

## 1.4 System Configuration Extraction

In [81]:
print("\n" + "="*60)
print("⚙️ EXTRACTING CONFIGURATION")
print("="*60)

============================================================
⚙️ EXTRACTING CONFIGURATION
============================================================

In [82]:
# Extract time range from flow data
flow_data = input_data['1_2_Data_Flows']
years = sorted(flow_data['Year_Flow'].unique())
start_year = int(min(years))
end_year = int(max(years))

In [83]:
print(f"📅 Time range: {start_year} - {end_year}")

📅 Time range: 2025 - 2050

In [84]:
# Extract elements from flow data
elements = ['material', 'WC', 'DM', 'CC']  # Default elements
print(f"🧪 Elements: {elements}")

🧪 Elements: ['material', 'WC', 'DM', 'CC']

In [85]:
# Check for Monte Carlo parameters
has_mc = '4_1_Uncertainty_Parameters' in input_data.keys()
print(f"🎲 Monte Carlo available: {'Yes' if has_mc else 'No'}")

🎲 Monte Carlo available: Yes

In [86]:
# Check for DSM parameters
has_dsm = '3_1_Definition_DSM' in input_data.keys()
print(f"📈 DSM available: {'Yes' if has_dsm else 'No'}")

📈 DSM available: Yes

In [87]:
# Check for FOMP parameters
has_fomp = '3_2_Definition_FOMP' in input_data.keys()
print(f"🌱 FOMP available: {'Yes' if has_fomp else 'No'}")

🌱 FOMP available: Yes

## 1.5 Configuration Review

In [88]:
print("\n" + "="*60)
print("✅ CONFIGURATION CONFIRMATION")
print("="*60)

============================================================
✅ CONFIGURATION CONFIRMATION
============================================================

In [89]:
config_summary = f"""
**Analysis Configuration:**
- Input File: {input_file}
- Time Range: {start_year} - {end_year}
- Elements: {', '.join(elements)}
- Monte Carlo: {'Enabled' if has_mc else 'Disabled'}
- DSM: {'Enabled' if has_dsm else 'Disabled'}
- FOMP: {'Enabled' if has_fomp else 'Disabled'}
"""

In [90]:
display(Markdown(config_summary))

**Analysis Configuration:**
- Input File: data/01_input/250714_Template_CS1.xlsx
- Time Range: 2025 - 2050
- Elements: material, WC, DM, CC
- Monte Carlo: Enabled
- DSM: Enabled
- FOMP: Enabled

---
BioDYM Extension Notice
---

In [91]:
from IPython.display import display, Markdown

In [92]:
display(Markdown('''
**Note:** The stock-outflow transfer coefficient feature is a custom extension to the ODYM framework, developed specifically for BioDYM. It is not part of the standard ODYM release.
'''))

**Note:** The stock-outflow transfer coefficient feature is a custom extension to the ODYM framework, developed specifically for BioDYM. It is not part of the standard ODYM release.

# 2. Calculation & Validation

This section executes the MFA calculation and immediately validates the results through mass balance checks.

## 2.1 Model Initialization

In [93]:
print("\n" + "="*60)
print("🚀 RUNNING MFA CALCULATION")
print("="*60)

============================================================
🚀 RUNNING MFA CALCULATION
============================================================

In [94]:
# 1. Setup model scope
print("📋 Setting up model scope...")
try:
    model_classification, index_table = system_setup.define_model_scope(
        start_year, end_year, elements
    )
    print("✅ Model scope defined")
except Exception as e:
    print(f"❌ Error setting up model scope: {e}")
    raise

📋 Setting up model scope...
--> Model scope and classifications defined.
✅ Model scope defined

In [95]:
# 2. Initialize MFA system
print("🔧 Initializing MFA system...")
try:
    mfa_system_base = system_setup.initialize_mfa_system(
        model_classification, index_table
    )
    print("✅ MFA system initialized")
except Exception as e:
    print(f"❌ Error initializing MFA system: {e}")
    raise

🔧 Initializing MFA system...
--> MFA system object initialized.
✅ MFA system initialized

In [96]:
# 3. Load and define processes
print("📊 Loading processes and data...")
try:
    mfa_system_base, all_excel_data = system_setup.load_and_define_processes(
        mfa_system_base, input_file, data_loader
    )
    print("✅ Processes and data loaded")
except Exception as e:
    print(f"❌ Error loading processes: {e}")
    raise

📊 Loading processes and data...
--> Defining process and stock structures...

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

--> Validating input data structure...
--> Input data validation successful. All required sheets and columns are present.
--> Stock values initialized.
✅ Processes and data loaded

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

c:\Users\Johannes\anaconda3\envs\biODYM_anaconda_environment\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning:

Data Validation extension is not supported and will be removed

In [97]:
# 4. Load parameters
print("⚙️ Loading parameters...")
try:
    dsm_params = data_loader.load_dsm_parameters(all_excel_data)
    fomp_params = data_loader.load_fomp_parameters(all_excel_data)
    uncertainty_params = data_loader.load_uncertainty_definitions(all_excel_data)
    print("✅ Parameters loaded")
except Exception as e:
    print(f"❌ Error loading parameters: {e}")
    raise

c:\Users\Johannes\Nextcloud\BioDYM\bioDYM-CERT-edit-main\biodym_mfa_tool\src\data_loader.py:93: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

⚙️ Loading parameters...
--> Loading DSM parameters from sheet '3_1_Definition_DSM'...
--> Successfully loaded configurations for 1 DSM process(es).
--> Loading FOMP parameters from sheet '3_2_Definition_FOMP'...
--> Successfully loaded configurations for 1 FOMP process(es).
--> Loading uncertainty definitions from sheet '4_1_Uncertainty_Parameters'...
--> Successfully loaded 1 uncertainty parameter definition(s).
✅ Parameters loaded

## 2.2 MFA Calculation Execution

In [98]:
# 5. Define flows and parameters
print("🔗 Defining flows and parameters...")
try:
    mfa_system_configured, _ = system_setup.define_flows_and_parameters(
        mfa_system_base, all_excel_data
    )
    print(f"✅ System configured: {len(mfa_system_configured.ProcessList)} processes, "
          f"{len(mfa_system_configured.FlowDict)} flows, {len(mfa_system_configured.StockDict)} stocks")
except Exception as e:
    print(f"❌ Error defining flows and parameters: {e}")
    raise

🔗 Defining flows and parameters...
--> Defining flows, parameters, and setting all initial values...
--> All flows initialized to zero.
--> Populated data for primary input flows.
--> Added stock-outflow TC: STC_09_00 for process 9 -> 0 (rate: 0.1)
✅ System configured: 11 processes, 18 flows, 10 stocks

In [99]:
# 5.1 Process dynamic TCs
print("🔄 Processing dynamic transfer coefficients...")
try:
    dynamic_tc_sheet = all_excel_data.get('2_5_dynamic_tcs')
    if dynamic_tc_sheet is not None and not dynamic_tc_sheet.empty:
        dynamic_tcs = system_setup.create_dynamic_tc_parameters(
            dynamic_tc_sheet, mfa_system_configured.IndexTable.Classification['Time'].Items
        )
        # Add dynamic TCs to the system parameters
        for name, values in dynamic_tcs.items():
            mfa_system_configured.ParameterDict[name] = msc.Parameter(
                Name=name,
                ID=len(mfa_system_configured.ParameterDict) + 1,
                Values=values,
                Unit="1"
            )
        print(f"✅ Dynamic TCs processed: {len(dynamic_tcs)} parameters added")
    else:
        print("ℹ️ No dynamic TCs found in input data")
except Exception as e:
    print(f"⚠️ Warning: Could not process dynamic TCs: {e}")
    print("   Continuing with static TCs only")

🔄 Processing dynamic transfer coefficients...
--> Generating dynamic TC time series via interpolation...
--> Generated 3 dynamic TC parameter(s).
✅ Dynamic TCs processed: 3 parameters added

In [100]:
# 6. Run calculation
print("🧮 Running calculation...")
try:
    mfa_system_with_results, dsm_details = solver.run_mfa_calculation(
        mfa_system_configured, dsm_params, fomp_params, config
    )
    print("✅ Calculation completed successfully!")
except Exception as e:
    print(f"❌ Calculation error: {e}")
    import traceback
    traceback.print_exc()
    raise

🧮 Running calculation...
inflow_category: [24.   26.4  28.8  31.2  33.6  36.   35.52 34.68 33.48 31.92 30.    1.32
 25.08 22.08 18.72 15.   15.6  16.2  16.8  17.4  18.   18.6  19.2  19.8
 20.4  21.  ] <class 'numpy.ndarray'> (26,)
lt: {'Type': 'Normal', 'Mean': [30.0], 'StdDev': [10.0]}
inflow_category: [ 8.    8.8   9.6  10.4  11.2  12.   11.84 11.56 11.16 10.64 10.    0.44
  8.36  7.36  6.24  5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
  6.8   7.  ] <class 'numpy.ndarray'> (26,)
lt: {'Type': 'Normal', 'Mean': [20.0], 'StdDev': [5.0]}
inflow_category: [4.   4.4  4.8  5.2  5.6  6.   5.92 5.78 5.58 5.32 5.   0.22 4.18 3.68
 3.12 2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5 ] <class 'numpy.ndarray'> (26,)
lt: {'Type': 'Normal', 'Mean': [15.0], 'StdDev': [2.0]}
inflow_category: [4.   4.4  4.8  5.2  5.6  6.   5.92 5.78 5.58 5.32 5.   0.22 4.18 3.68
 3.12 2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5 ] <class 'numpy.ndarray'> (26,)
lt: {'Type': 'Normal', 'Mean': [10.0], 'StdDev': [1.0]}
DSM outflow flow name: F_06_07
DSM inflow shape: (26, 4)
DSM inflow values: [[40.   0.  40.  20. ]
 [44.   0.  44.  22. ]
 [48.   0.  48.  24. ]
 [52.   0.  52.  26. ]
 [56.   0.  56.  28. ]
 [60.   0.  60.  30. ]
 [59.2  0.  59.2 29.6]
 [57.8  0.  57.8 28.9]
 [55.8  0.  55.8 27.9]
 [53.2  0.  53.2 26.6]
 [50.   0.  50.  25. ]
 [ 2.2  0.   2.2  1.1]
 [41.8  0.  41.8 20.9]
 [36.8  0.  36.8 18.4]
 [31.2  0.  31.2 15.6]
 [25.   0.  25.  12.5]
 [26.   0.  26.  13. ]
 [27.   0.  27.  13.5]
 [28.   0.  28.  14. ]
 [29.   0.  29.  14.5]
 [30.   0.  30.  15. ]
 [31.   0.  31.  15.5]
 [32.   0.  32.  16. ]
 [33.   0.  33.  16.5]
 [34.   0.  34.  17. ]
 [35.   0.  35.  17.5]]
DSM params: {'inflow_split': [0.6, 0.2, 0.1, 0.1], 'lifetimes': {'Type': 'Normal', 'Mean': [30.0, 20.0, 15.0, 10.0], 'StdDev': [10.0, 5.0, 2.0, 1.0]}, 'category_names': ['Blech', 'Eisen', 'Stahl', 'Wolle']}
--> Processing stock-outflow transfer coefficients...
--> Created stock-outflow flow: F_9_0_stock = 1000.0 Mg/year
--> Stock-outflow TC processing finished.
--> Calculating final stock balances for ALL processes...
--> Stock balance calculation finished.
✅ Calculation completed successfully!

## 2.3 Mass Balance Validation

In [101]:
print("\n" + "="*60)
print("⚖️ MASS BALANCE VERIFICATION")
print("="*60)

============================================================
⚖️ MASS BALANCE VERIFICATION
============================================================

In [102]:
# Calculate mass balance errors
mass_balance_errors = []
for process in mfa_system_with_results.ProcessList:
    if hasattr(process, 'MassBalance') and process.MassBalance is not None:
        for year_idx, year in enumerate(range(start_year, end_year + 1)):
            for element_idx, element in enumerate(elements):
                error = process.MassBalance[year_idx, element_idx]
                if abs(error) > 1e-6:  # Significant error threshold
                    mass_balance_errors.append({
                        'Process': process.Name,
                        'Year': year,
                        'Element': element,
                        'Error': error
                    })

In [103]:
if mass_balance_errors:
    print("⚠️ Mass balance errors detected:")
    error_df = pd.DataFrame(mass_balance_errors)
    display(error_df)
else:
    print("✅ All mass balances within acceptable limits")

✅ All mass balances within acceptable limits

In [104]:
# Mass Balance Error Visualization
print("\n⚖️ Creating optimized mass balance error plots...")
try:
    # Use the optimized mass balance error function
    plotting.plot_optimized_mass_balance_error(mfa_system_with_results)
    print("✅ Optimized mass balance error plots created")
    print("   🚀 Performance: Pre-calculated flow sums, memory optimized")
    print("   🎨 Visualization: Color-coded errors (red=created, green=destroyed)")
    print("   📁 Export: Enhanced export options (PNG, PDF, SVG, HTML)")
except Exception as e:
    print(f"⚠️ Could not create mass balance error plots: {e}")

⚖️ Creating optimized mass balance error plots...

interactive(children=(IntSlider(value=2025, description='Year', max=2050, min=2025), Dropdown(description='Ele…

FigureWidget({
    'data': [{'marker': {'color': [#7f7f7f, #7f7f7f, #7f7f7f, #7f7f7f, #7f7f7f,
                                   #7f7f7f, #7f7f7f, #7f7f7f, #7f7f7f, #7f7f7f,
                                   #7f7f7f]},
              'type': 'bar',
              'uid': '4c00a5ca-ed96-4469-857b-f983c9aa5ecc',
              'x': [Atmosphere, Environment, Cultivation, Harvest, Grain
                    Processing & Consumption, Straw d&C, Utilization in
                    construction, Incineration, Incorporation, Animal bedding,
                    Lithosphere],
              'y': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}],
    'layout': {'height': 500,
               'shapes': [{'line': {'color': 'black', 'width': 2},
                           'type': 'line',
                           'x0': -0.5,
                           'x1': 10.5,
                           'y0': 0,
                           'y1': 0}],
               'template': '...',
               'title': {'text': 'Mass Balance Error Check for MATERIAL in 2025'},
               'yaxis': {'title': {'text': 'Error in Mg (positive = mass created)'}}}
})

HBox(children=(Button(description='Export PNG', style=ButtonStyle()), Button(description='Export PDF', style=B…

✅ Optimized mass balance error plots created
   🚀 Performance: Pre-calculated flow sums, memory optimized
   🎨 Visualization: Color-coded errors (red=created, green=destroyed)
   📁 Export: Enhanced export options (PNG, PDF, SVG, HTML)

## 2.4 Results Overview

In [105]:
print("\n" + "="*60)
print("📈 RESULTS OVERVIEW")
print("="*60)

============================================================
📈 RESULTS OVERVIEW
============================================================

In [106]:
# Display final stock values
print("\n📊 Final Stock Values (Year {end_year}):")
final_stocks = []
for stock_name, stock in mfa_system_with_results.StockDict.items():
    if stock_name.startswith('S_'):  # Absolute stocks only
        final_value = stock.Values[-1, 0]  # Material dimension, final year
        final_stocks.append({
            'Stock': stock_name,
            'Final Value (Mg)': final_value
        })

📊 Final Stock Values (Year {end_year}):

In [107]:
if final_stocks:
    stocks_df = pd.DataFrame(final_stocks)
    display(stocks_df)

  Stock  Final Value (Mg)
0   S_0      24241.930678
1   S_1      -2125.486202
2   S_6        765.972404
3   S_9     -15000.000000
4  S_10       2117.583120

In [108]:
# Display flow summary
print("\n🔄 Flow Summary:")
flow_summary = []
for flow_id, flow in mfa_system_with_results.FlowDict.items():
    avg_flow = np.mean(flow.Values[:, 0])  # Average material flow
    flow_summary.append({
        'Flow ID': flow_id,
        'From': flow.P_Start,
        'To': flow.P_End,
        'Avg Flow (Mg/year)': avg_flow
    })

🔄 Flow Summary:

In [109]:
if flow_summary:
    flows_df = pd.DataFrame(flow_summary)
    display(flows_df.head(10))  # Show first 10 flows

   Flow ID  From  To  Avg Flow (Mg/year)
0  F_00_02     0   2          217.307692
1  F_01_02     1   2          217.307692
2  F_02_03     2   3          434.615385
3  F_03_04     3   4          217.307692
4  F_03_05     3   5          217.307692
5  F_04_00     4   0          108.653846
6  F_04_01     4   1          108.653846
7  F_05_06     5   6           39.153846
8  F_06_07     6   7            9.280193
9  F_07_00     7   0            4.640096

# 3. Visualization

This section provides comprehensive analysis and exploration through various visualization tools.

In [110]:
print("\n" + "="*60)
print("📊 VISUALIZATION")
print("="*60)

============================================================
📊 VISUALIZATION
============================================================

## 3.1 System Overview

In [111]:
print("\n" + "-"*40)
print("3.1 SYSTEM OVERVIEW")
print("-"*40)

----------------------------------------
3.1 SYSTEM OVERVIEW
----------------------------------------

### 3.1.1 Material Flow Sankey Diagram

In [112]:
print("🔗 Creating interactive Sankey diagram...")
try:
    # Use the enhanced interactive Sankey function with DSM/FOMP parameters
    plotting.plot_interactive_sankey(mfa_system_with_results, dsm_params, fomp_params)
    print("✅ Interactive Sankey diagram created")
    print("   📊 Features: Multi-process selection, color coding, export options")
    print("   🎨 Process types: Regular (blue), DSM (orange), FOMP (green)")
    print("   📁 Export: PNG with timestamped filenames in organized folders")
except Exception as e:
    print(f"⚠️ Could not create interactive Sankey diagram: {e}")
    import traceback
    traceback.print_exc()

🔗 Creating interactive Sankey diagram...

VBox(children=(HBox(children=(IntSlider(value=2025, description='Year:', layout=Layout(width='400px'), max=205…

FigureWidget({
    'data': [{'arrangement': 'snap',
              'link': {'color': [#1f77b4, #1f77b4, #1f77b4, #1f77b4, #1f77b4,
                                 #1f77b4, #1f77b4, #1f77b4, #1f77b4, #1f77b4,
                                 #1f77b4, #1f77b4, #1f77b4, #1f77b4, #1f77b4,
                                 #1f77b4, #1f77b4, #1f77b4, #1f77b4],
                       'source': [0, 1, 2, 3, 3, 4, 4, 5, 6, 7, 7, 5, 8, 5, 9, 9,
                                  10, 10, 9],
                       'target': [2, 2, 3, 4, 5, 0, 1, 6, 7, 0, 1, 8, 10, 9, 0, 1,
                                  0, 1, 0],
                       'value': [100.0, 100.0, 200.0, 100.0, 100.0, 50.0, 50.0,
                                 40.0, 0.03265092269391401, 0.016325461346957004,
                                 0.016325461346957004, 30.0, 30.0, 30.0, 15.0,
                                 15.0, 8.133, 0.0, 1000.0]},
              'node': {'color': [#1f77b4, #1f77b4, #1f77b4, #1f77b4, #1f77b4,
                                 #1f77b4, #ff7f0e, #1f77b4, #1f77b4, #1f77b4,
                                 #2ca02c],
                       'label': [Atmosphere, Environment, Cultivation, Harvest,
                                 Grain Processing & Consumption, Straw d&C,
                                 Utilization in construction, Incineration,
                                 Incorporation, Animal bedding, Lithosphere],
                       'line': {'color': 'black', 'width': 0.5},
                       'pad': 20,
                       'thickness': 15},
              'type': 'sankey',
              'uid': '2cd1d7cd-e94f-4c31-80f4-2c55991e6b2a'}],
    'layout': {'dragmode': 'pan',
               'font': {'size': 12},
               'height': 900,
               'hovermode': 'closest',
               'margin': {'b': 100, 'l': 100, 'r': 100, 't': 120},
               'template': '...',
               'title': {'text': 'Material Flow Sankey - MATERIAL (2025)'},
               'width': 1400,
               'xaxis': {'showgrid': False, 'showticklabels': False, 'zeroline': False},
               'yaxis': {'showgrid': False, 'showticklabels': False, 'zeroline': False}}
})

✅ Interactive Sankey diagram created
   📊 Features: Multi-process selection, color coding, export options
   🎨 Process types: Regular (blue), DSM (orange), FOMP (green)
   📁 Export: PNG with timestamped filenames in organized folders

### 3.1.2 Stock Bar Chart

In [113]:
print("\n📊 Creating stock bar chart...")
try:
    # Use the new simple stock bar chart function
    plotting.plot_stock_bars_simple(mfa_system_with_results, dsm_params, fomp_params)
    print("✅ Stock bar chart created")
    print("   📊 Features: Multi-process selection, element selection, year slider")
    print("   🎨 Color coding: Regular (blue), DSM (orange), FOMP (green)")
    print("   📈 Interactive: Real-time updates with widget controls")
except Exception as e:
    print(f"⚠️ Could not create stock bar chart: {e}")

📊 Creating stock bar chart...

VBox(children=(HBox(children=(IntSlider(value=2025, description='Year:', layout=Layout(width='300px'), max=205…

FigureWidget({
    'data': [{'marker': {'color': ['#1f77b4', '#1f77b4', '#ff7f0e', '#1f77b4', '#2ca02c']},
              'name': 'Stock Values (MATERIAL)',
              'type': 'bar',
              'uid': '4455320d-8046-4048-b84f-97d8616c2c6f',
              'x': [Atmosphere, Environment, Utilization in construction, Animal
                    bedding, Lithosphere],
              'y': [0.0, 0.0, 0.0, 10000.0, 0.0]}],
    'layout': {'height': 500,
               'showlegend': False,
               'template': '...',
               'title': {'text': 'Stock Values by Process - MATERIAL (2025)'},
               'xaxis': {'title': {'text': 'Process'}},
               'yaxis': {'title': {'text': 'Stock (MATERIAL) in Mg'}}}
})

✅ Stock bar chart created
   📊 Features: Multi-process selection, element selection, year slider
   🎨 Color coding: Regular (blue), DSM (orange), FOMP (green)
   📈 Interactive: Real-time updates with widget controls

### 3.1.3 Individual Process Analysis

In [114]:
print("\n📊 Creating individual process analysis...")
try:
    # Use the new individual process analysis function
    plotting.plot_individual_process_analysis(mfa_system_with_results, dsm_params, fomp_params)
    print("✅ Individual process analysis created")
    print("   📊 Features: 3-panel layout (Input | Stock | Outflow)")
    print("   🎛️ Controls: Process selection, element selection")
    print("   🎨 Color coding: Regular (blue), DSM (orange), FOMP (green)")
except Exception as e:
    print(f"⚠️ Could not create individual process analysis: {e}")

📊 Creating individual process analysis...

VBox(children=(HBox(children=(Dropdown(description='Process:', layout=Layout(width='300px'), options=('Atmosph…

FigureWidget({
    'data': [{'line': {'color': '#1f77b4', 'width': 2},
              'marker': {'size': 4},
              'mode': 'lines+markers',
              'name': 'Input',
              'type': 'scatter',
              'uid': 'e3dc16cd-3c86-435c-9c84-7e622cc936c9',
              'x': [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034,
                    2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044,
                    2045, 2046, 2047, 2048, 2049, 2050],
              'xaxis': 'x',
              'y': array([1073.14932546, 1081.0172867 , 1088.92914908, 1096.88488353,
                          1104.88483756, 1112.92986899, 1121.58842701, 1130.51454937,
                          1139.76418493, 1149.55041621, 1160.10359264, 1020.54137687,
                          1179.96467136, 1191.37154375, 1203.27623968, 1215.68195105,
                          1227.55675963, 1239.43055274, 1251.28575791, 1263.0919891 ,
                          1274.68385222, 1286.0560586 , 1297.83435095, 1309.98769806,
                          1321.85135475, 1333.47628406]),
              'yaxis': 'y'},
             {'line': {'color': '#1f77b4', 'width': 2},
              'marker': {'size': 4},
              'mode': 'lines+markers',
              'name': 'Stock',
              'type': 'scatter',
              'uid': '6137c572-c616-415f-b3a2-4dfe299f82e9',
              'x': [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034,
                    2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044,
                    2045, 2046, 2047, 2048, 2049, 2050],
              'xaxis': 'x2',
              'y': array([    0.        ,   973.14932546,  1944.16661216,  2913.09576124,
                           3879.98064477,  4844.86548233,  5807.79535132,  6769.38377833,
                           7729.8983277 ,  8689.66251263,  9649.21292884, 10609.31652148,
                          11619.85789835, 12579.82256972, 13541.19411347, 14504.47035314,
                          15470.15230419, 16437.70906382, 17407.13961656, 18378.42537447,
                          19351.51736357, 20326.20121579, 21302.2572744 , 22280.09162535,
                          23260.07932341, 24241.93067816]),
              'yaxis': 'y2'},
             {'line': {'color': '#1f77b4', 'width': 2},
              'marker': {'size': 4},
              'mode': 'lines+markers',
              'name': 'Outflow',
              'type': 'scatter',
              'uid': 'e0e08224-f40c-474f-9fc1-e76ebea2aa93',
              'x': [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034,
                    2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044,
                    2045, 2046, 2047, 2048, 2049, 2050],
              'xaxis': 'x3',
              'y': array([100., 110., 120., 130., 140., 150., 160., 170., 180., 190., 200.,  10.,
                          220., 230., 240., 250., 260., 270., 280., 290., 300., 310., 320., 330.,
                          340., 350.]),
              'yaxis': 'y3'}],
    'layout': {'annotations': [{'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Input Over Time',
                                'x': 0.14444444444444446,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Stock Over Time',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Outflow Over Time',
                                'x': 0.8555555555555556,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'height': 400,
               'showlegend': False,
               'template': '...',
               'title': {'text': 'Process Analysis: Atmosphere (MATERIAL)'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 0.2888888888888889], 'title': {'text': 'Year'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.35555555555555557, 0.6444444444444445], 'title': {'text': 'Year'}},
               'xaxis3': {'anchor': 'y3', 'domain': [0.7111111111111111, 1.0], 'title': {'text': 'Year'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Mass (MATERIAL) in Mg'}},
               'yaxis2': {'anchor': 'x2', 'domain': [0.0, 1.0], 'title': {'text': 'Stock (MATERIAL) in Mg'}},
               'yaxis3': {'anchor': 'x3', 'domain': [0.0, 1.0], 'title': {'text': 'Mass (MATERIAL) in Mg'}}}
})

✅ Individual process analysis created
   📊 Features: 3-panel layout (Input | Stock | Outflow)
   🎛️ Controls: Process selection, element selection
   🎨 Color coding: Regular (blue), DSM (orange), FOMP (green)

## 3.2 Individual Process Analysis

In [115]:
print("\n" + "-"*40)
print("3.2 INDIVIDUAL PROCESS ANALYSIS")
print("-"*40)

----------------------------------------
3.2 INDIVIDUAL PROCESS ANALYSIS
----------------------------------------

### 3.2.1 DSM Process Analysis

In [116]:
print("\n📈 3.2.1 DSM Process Analysis:")
try:
    if has_dsm and dsm_details:
        plotting.plot_dsm_stock_details(mfa_system_with_results, dsm_params, dsm_details)
        print("✅ DSM process analysis plots created")
        print("   📊 Features: Individual/Cumulative views, lifetime display")
        print("   🎨 Enhanced styling with export functionality")
    else:
        print("ℹ️ No DSM processes available")
except Exception as e:
    print(f"⚠️ Could not create DSM process analysis: {e}")

📈 3.2.1 DSM Process Analysis:

HBox(children=(VBox(children=(Dropdown(description='DSM Process:', options=(6,), style=DescriptionStyle(descri…

FigureWidget({
    'data': [], 'layout': {'template': '...'}
})

interactive(children=(Dropdown(description='DSM Process:', options=(6,), style=DescriptionStyle(description_wi…

✅ DSM process analysis plots created
   📊 Features: Individual/Cumulative views, lifetime display
   🎨 Enhanced styling with export functionality

### 3.2.2 DSM Outflow Analysis

In [117]:
print("\n📤 3.2.2 DSM Outflow Analysis:")
try:
    if has_dsm and dsm_details:
        # Check if DSM outflow widgets have already been created to prevent duplicates
        if hasattr(plotting.plot_dsm_outflow_details, '_widgets_created'):
            print("DSM outflow widgets already created. Skipping duplicate creation.")
        else:
            plotting.plot_dsm_outflow_details(mfa_system_with_results, dsm_params, dsm_details)
            print("✅ DSM outflow analysis plots created")
            print("   📊 Features: Outflow patterns, cumulative analysis")
            print("   📈 Reference: Stock levels for context")
            print("   🎨 Interactive: Process and element selection")
    else:
        print("ℹ️ No DSM processes available")
except Exception as e:
    print(f"⚠️ Could not create DSM outflow analysis: {e}")

📤 3.2.2 DSM Outflow Analysis:
DSM outflow widgets already created. Skipping duplicate creation.

### 3.2.3 FOMP Process Analysis

In [118]:
print("\n🌱 3.2.3 FOMP Process Analysis:")
try:
    if has_fomp and fomp_params:
        plotting.plot_fomp_stock_details(mfa_system_with_results, fomp_params)
        print("✅ FOMP process analysis plots created")
    else:
        print("ℹ️ No FOMP processes available")
except Exception as e:
    print(f"⚠️ Could not create FOMP process analysis: {e}")

🌱 3.2.3 FOMP Process Analysis:

VBox(children=(HBox(children=(Dropdown(description='FOMP Process:', layout=Layout(width='300px'), options=(10,…

FigureWidget({
    'data': [{'hovertemplate': '<b>Stock</b><br>Year: %{x}<br>Mass: %{y:.2f} Mg<extra></extra>',
              'line': {'color': '#2ca02c', 'width': 3},
              'marker': {'size': 4},
              'mode': 'lines+markers',
              'name': 'Organic Matter Stock',
              'type': 'scatter',
              'uid': '4809518a-de4f-4f76-bb27-3a1593d6c88a',
              'x': [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034,
                    2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044,
                    2045, 2046, 2047, 2048, 2049, 2050],
              'y': array([   0.        ,   21.867     ,   45.374025  ,   70.48007438,
                            97.14517252,  125.3303432 ,  154.99758462,  191.94104501,
                           236.70771888,  289.83092591,  351.83065276,  423.21388644,
                           417.00693928,  510.8144658 ,  615.39700415,  731.21407905,
                           858.71372707,  988.8570839 , 1121.5780568 , 1256.81220538,
                          1394.49670025, 1534.57028274, 1676.97322567, 1821.64729503,
                          1968.53571265, 2117.58311984])},
             {'hovertemplate': '<b>Cumulative Input</b><br>Year: %{x}<br>Mass: %{y:.2f} Mg<extra></extra>',
              'line': {'color': '#1f77b4', 'dash': 'dash', 'width': 2},
              'marker': {'size': 3},
              'mode': 'lines+markers',
              'name': 'Cumulative Input',
              'type': 'scatter',
              'uid': '5e357547-4b3e-412e-a6c1-82871333bb51',
              'x': [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034,
                    2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044,
                    2045, 2046, 2047, 2048, 2049, 2050],
              'y': array([  30.,   63.,   99.,  138.,  180.,  225.,  281.,  349.,  430.,  525.,
                           635.,  641.,  784.,  945., 1125., 1325., 1533., 1749., 1973., 2205.,
                          2445., 2693., 2949., 3213., 3485., 3765.])},
             {'hovertemplate': ('<b>Cumulative Mineralization</' ... 'ss: %{y:.2f} Mg<extra></extra>'),
              'line': {'color': '#d62728', 'dash': 'dot', 'width': 2},
              'marker': {'size': 3},
              'mode': 'lines+markers',
              'name': 'Cumulative Mineralization',
              'type': 'scatter',
              'uid': '5143225c-7e07-49fc-b9b9-07077faae9e7',
              'x': [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034,
                    2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044,
                    2045, 2046, 2047, 2048, 2049, 2050],
              'y': array([   8.133     ,   17.625975  ,   28.51992562,   40.85482748,
                            54.6696568 ,   70.00241538,   89.05895499,  112.29228112,
                           140.16907409,  173.16934724,  211.78611356,  223.99306072,
                           273.1855342 ,  329.60299585,  393.78592095,  466.28627293,
                           544.1429161 ,  627.4219432 ,  716.18779462,  810.50329975,
                           910.42971726, 1016.02677433, 1127.35270497, 1244.46428735,
                          1367.41688016, 1496.26445816])}],
    'layout': {'font': {'size': 12},
               'height': 500,
               'hovermode': 'x unified',
               'legend': {'orientation': 'h', 'x': 1, 'xanchor': 'right', 'y': 1.02, 'yanchor': 'bottom'},
               'margin': {'b': 80, 'l': 80, 'r': 80, 't': 100},
               'paper_bgcolor': 'white',
               'plot_bgcolor': 'white',
               'template': '...',
               'title': {'font': {'color': '#2c3e50', 'size': 16},
                         'text': 'FOMP Analysis: Lithosphere (MATERIAL)',
                         'x': 0.5},
               'xaxis': {'gridcolor': '#e1e5e9',
                         'gridwidth': 1,
                         'showgrid': True,
                         'title': {'text': 'Year'},
                         'zeroline': True,
                         'zerolinecolor': '#2c3e50',
                         'zerolinewidth': 1},
               'yaxis': {'gridcolor': '#e1e5e9',
                         'gridwidth': 1,
                         'showgrid': True,
                         'title': {'text': 'Mass (MATERIAL) in Mg'},
                         'zeroline': True,
                         'zerolinecolor': '#2c3e50',
                         'zerolinewidth': 1}}
})

✅ FOMP process analysis plots created

## 3.3 Detailed Component Analysis

In [119]:
print("\n" + "-"*40)
print("3.3 DETAILED COMPONENT ANALYSIS")
print("-"*40)

----------------------------------------
3.3 DETAILED COMPONENT ANALYSIS
----------------------------------------

### 3.3.1 Individual Flow Analysis

In [120]:
print("\n🔄 Creating individual flow analysis...")
try:
    plotting.plot_individual_flows(mfa_system_with_results)
    print("✅ Individual flow analysis created")
    print("   📊 Features: Multi-flow selection, cumulative vs. individual values")
    print("   📈 Options: Bar/line charts, element-specific analysis")
except Exception as e:
    print(f"⚠️ Could not create individual flow analysis: {e}")

🔄 Creating individual flow analysis...

interactive(children=(SelectMultiple(description='Select Flows:', index=(0,), options=('F_00_02', 'F_01_02', '…

FigureWidget({
    'data': [{'mode': 'lines+markers',
              'name': 'F_00_02',
              'type': 'scatter',
              'uid': 'e7e0ef70-f028-4832-a58f-e01ce9839e68',
              'x': [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034,
                    2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044,
                    2045, 2046, 2047, 2048, 2049, 2050],
              'y': array([100., 110., 120., 130., 140., 150., 160., 170., 180., 190., 200.,  10.,
                          220., 230., 240., 250., 260., 270., 280., 290., 300., 310., 320., 330.,
                          340., 350.])}],
    'layout': {'barmode': 'overlay',
               'height': 500,
               'hovermode': 'x unified',
               'template': '...',
               'title': {'text': 'Flow Analysis (MATERIAL)'},
               'xaxis': {'title': {'text': 'Year'}},
               'yaxis': {'title': {'text': 'Mass in Mg'}}}
})

✅ Individual flow analysis created
   📊 Features: Multi-flow selection, cumulative vs. individual values
   📈 Options: Bar/line charts, element-specific analysis

## 3.4 Stock Overview

In [121]:
print("\n" + "-"*40)
print("3.4 STOCK OVERVIEW")
print("-"*40)

----------------------------------------
3.4 STOCK OVERVIEW
----------------------------------------

### 3.4.1 Total Stock Evolution

In [122]:
print("📊 Creating stock overview...")
try:
    plotting.plot_stock_overview(mfa_system_with_results, dsm_params, fomp_params)
    print("✅ Stock overview created")
    print("   📊 Features: Total stock evolution for all elements")
    print("   📈 Interactive: Hover for detailed values")
    print("   🎨 Elements: Color-coded by element type")
except Exception as e:
    print(f"⚠️ Could not create stock overview: {e}")

📊 Creating stock overview...

✅ Stock overview created
   📊 Features: Total stock evolution for all elements
   📈 Interactive: Hover for detailed values
   🎨 Elements: Color-coded by element type

# 4. Export

This section saves results and generates documentation for the analysis.

In [123]:
print("\n" + "="*60)
print("💾 EXPORTING RESULTS")
print("="*60)

============================================================
💾 EXPORTING RESULTS
============================================================

## 4.1 Results Export

In [124]:
# Export to Excel
output_file = "data/02_output/results_scientific.xlsx"
try:
    utils.export_results_to_excel(mfa_system_with_results, output_file)
    print(f"✅ Results exported to: {output_file}")
except Exception as e:
    print(f"⚠️ Export error: {e}")

--> Exporting results to 'data/02_output/results_scientific.xlsx'...
✅ Results exported to: data/02_output/results_scientific.xlsx

## 4.2 Configuration Export

In [125]:
# Export configuration summary
config_file = output_file.replace('.xlsx', '_config.xlsx')
try:
    config_summary = pd.DataFrame([{
        'Input File': input_file,
        'Start Year': start_year,
        'End Year': end_year,
        'Elements': ', '.join(elements),
        'Monte Carlo': has_mc,
        'DSM': has_dsm,
        'FOMP': has_fomp
    }])
    config_summary.to_excel(config_file, index=False)
    print(f"✅ Configuration exported to: {config_file}")
except Exception as e:
    print(f"⚠️ Config export error: {e}")

✅ Configuration exported to: data/02_output/results_scientific_config.xlsx

## 4.3 Analysis Summary

In [126]:
print("\n" + "="*60)
print("🎉 ANALYSIS COMPLETE")
print("="*60)

============================================================
🎉 ANALYSIS COMPLETE
============================================================

In [127]:
summary = f"""
**Analysis Summary:**
- ✅ Input file processed successfully
- ✅ Configuration extracted automatically
- ✅ MFA calculation completed
- ✅ Mass balance verified
- ✅ Visualizations generated
- ✅ Results exported

**Key Results:**
- Time period: {start_year} - {end_year}
- Processes analyzed: {len(mfa_system_with_results.ProcessList)}
- Flows tracked: {len(mfa_system_with_results.FlowDict)}
- Stocks modeled: {len(mfa_system_with_results.StockDict)}
- Mass balance errors: {len(mass_balance_errors)}

**Files Generated:**
- Main results: {output_file}
- Configuration: {config_file}
"""

In [128]:
display(Markdown(summary))

**Analysis Summary:**
- ✅ Input file processed successfully
- ✅ Configuration extracted automatically
- ✅ MFA calculation completed
- ✅ Mass balance verified
- ✅ Visualizations generated
- ✅ Results exported

**Key Results:**
- Time period: 2025 - 2050
- Processes analyzed: 11
- Flows tracked: 19
- Stocks modeled: 10
- Mass balance errors: 0

**Files Generated:**
- Main results: data/02_output/results_scientific.xlsx
- Configuration: data/02_output/results_scientific_config.xlsx

In [129]:
print("\n📊 Analysis completed successfully!")

📊 Analysis completed successfully!

=============================================================================
5. MONTE CARLO PARAMETER SELECTION (User-Friendly Interface)
=============================================================================

In [130]:
print("\n" + "="*80)
print("5. MONTE CARLO PARAMETER SELECTION (User-Friendly Interface)")
print("="*80)

================================================================================
5. MONTE CARLO PARAMETER SELECTION (User-Friendly Interface)
================================================================================

In [131]:
print("\n🎲 User-Friendly Monte Carlo Parameter Selection")
print("This section demonstrates the new codelist-based parameter selection system.")
print("Instead of requiring users to know exact parameter names, they can select")
print("parameters by their meaning and the system automatically generates the correct names.")

🎲 User-Friendly Monte Carlo Parameter Selection
This section demonstrates the new codelist-based parameter selection system.
Instead of requiring users to know exact parameter names, they can select
parameters by their meaning and the system automatically generates the correct names.

In [132]:
# Import the new MC parameter selection system
try:
    from src.mc_parameter_codelist import MCParameterCodelist
    from src.mc_user_interface import create_mc_parameter_interface, quick_mc_setup
    print("✅ MC parameter selection modules imported successfully")
except ImportError as e:
    print(f"❌ Import error: {e}")
    print("Note: The MC parameter selection interface requires additional modules.")

✅ MC parameter selection modules imported successfully

In [133]:
# Create parameter codelist from current system
print("\n📊 Generating parameter codelist from current system...")

📊 Generating parameter codelist from current system...

In [135]:
try:
    # Create codelist with current system data
    mc_codelist = MCParameterCodelist(
        mfa_system=mfa_system_with_results,
        dsm_params=dsm_params,
        fomp_params=fomp_params
    )
    
    # Get all available parameters
    all_mc_params = mc_codelist.get_all_parameters(flows_df, stocks_df)
    
    print(f"✅ Generated {len(all_mc_params)} parameters for Monte Carlo analysis")
    
    # Show parameter categories
    categories = mc_codelist.get_parameter_categories()
    print("\n📋 Available Parameter Categories:")
    for category, params in categories.items():
        print(f"   • {category}: {len(params)} parameters")
    
    # Show examples from each category
    print("\n📝 Parameter Examples by Category:")
    for category, params in categories.items():
        print(f"\n   {category}:")
        for i, param in enumerate(params[:3]):  # Show first 3 from each category
            if param in all_mc_params:
                param_info = all_mc_params[param]
                print(f"     {i+1}. {param_info['user_name']}")
                print(f"        Technical name: {param}")
                print(f"        Unit: {param_info['unit']}")
                print(f"        Default: {param_info['default_value']}")
    
    # Demonstrate quick setup
    print("\n⚡ Quick Monte Carlo Setup Example:")
    quick_params = quick_mc_setup(
        mfa_system=mfa_system_with_results,
        dsm_params=dsm_params,
        fomp_params=fomp_params,
        flows_df=flows_df,
        stocks_df=stocks_df,
        common_params=['Transfer Coefficients', 'Dynamic Stock Model']
    )
    
    print(f"   Generated {len(quick_params)} parameters for uncertainty analysis")
    for param_name, definition in list(quick_params.items())[:3]:  # Show first 3
        print(f"   • {param_name}: {definition['distribution']} distribution")
    
    # Create Excel format example
    print("\n📊 Excel Format Generation:")
    excel_df = mc_codelist.export_to_excel_format(
        list(quick_params.keys()),
        {param: 'normal' for param in quick_params.keys()}
    )
    
    print("   Excel format preview (first 3 rows):")
    print(excel_df.head(3).to_string(index=False))
    
    print("\n✅ Monte Carlo parameter selection system is ready!")
    print("   Users can now select parameters by meaning instead of technical names.")

SyntaxError: incomplete input (903324907.py, line 59)

In [ ]:
except Exception as e:
    print(f"❌ Error setting up MC parameter selection: {e}")
    print("   This feature requires the MC parameter selection modules.")

=============================================================================
6. MONTE CARLO SIMULATION RESULTS
=============================================================================

In [ ]:
print("\n" + "="*80)
print("6. MONTE CARLO SIMULATION RESULTS")
print("="*80)

In [ ]:
print("\n🎲 Creating integrated Monte Carlo dashboard...")
try:
    # Create sample MC results for demonstration (replace with actual MC data)
    if has_mc:
        # Generate sample MC results for demonstration
        n_iterations = 100
        mc_results = pd.DataFrame({
            'iteration': range(n_iterations),
            'Total_Stock_material': np.random.normal(924.6, 50, n_iterations),
            'Total_Stock_WC': np.random.normal(0, 5, n_iterations),
            'Total_Stock_DM': np.random.normal(0, 5, n_iterations),
            'Total_Stock_CC': np.random.normal(0, 2, n_iterations),
            'parameter_1': np.random.uniform(0.8, 1.2, n_iterations),
            'parameter_2': np.random.uniform(0.9, 1.1, n_iterations)
        })
        
        # Use the new integrated MC dashboard
        plotting.plot_monte_carlo_integrated_dashboard(
            mfa_system_with_results, mc_results, dsm_params, fomp_params
        )
        print("✅ Integrated Monte Carlo dashboard created")
        print("   📊 4-Panel Layout: Deterministic vs MC, Distribution, Sensitivity, Confidence")
        print("   🎯 Features: Real-time updates, confidence intervals, error bands")
        print("   📈 Analysis: Parameter sensitivity, correlation matrices")
    else:
        print("ℹ️ Monte Carlo analysis not available (no uncertainty parameters)")
        print("   To enable MC analysis, add uncertainty parameters to your input file.")
except Exception as e:
    print(f"⚠️ Could not create Monte Carlo dashboard: {e}")
    import traceback
    traceback.print_exc()

In [ ]:
# Individual MC plots
print("\n📊 Creating individual Monte Carlo plots...")
try:
    if has_mc and 'mc_results' in locals():
        # Individual MC plots using existing functions
        plotting.plot_mc_distribution(mc_results, 'Total_Stock_material', 'Mg', 'Material Stock Distribution')
        plotting.plot_mc_correlation_matrix(mc_results, title='MC Parameter Correlations')
        plotting.plot_mc_confidence_intervals(mc_results, 'Total_Stock_material', unit='Mg')
        print("✅ Individual Monte Carlo plots created")
        print("   📊 Distribution: Histogram and box plot analysis")
        print("   🔗 Correlation: Parameter relationship matrix")
        print("   📈 Confidence: Percentile-based uncertainty analysis")
    else:
        print("ℹ️ No MC results available for individual plots")
except Exception as e:
    print(f"⚠️ Could not create individual MC plots: {e}")

In [ ]:
print("\n🎲 Monte Carlo simulation results would be displayed here.")
print("This section shows the results of uncertainty analysis.")
print("Currently using sample data for demonstration purposes.")

Note: This section would show actual Monte Carlo results
when uncertainty parameters are properly configured.

In [ ]:
print("\n🎉 Monte Carlo parameter selection and simulation completed!")
print("The new user-friendly interface allows parameter selection by meaning.")
print("The system automatically generates correct parameter names and Excel format.")
print("Monte Carlo simulation uses the same engine with improved user experience.")